import { Geist, Geist_Mono } from "next/font/google";
import { Open_Sans, Poppins, Albert_Sans } from "next/font/google";
import localFont from "next/font/local"; // add
import "./globals.css";
import NavBar from "./components/navBar";
import Footer from "./components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "600", "700", "800"],
  display: "swap",
  style: ["normal", "italic"],
  variable: "--font-open-sans",
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  variable: "--font-poppins",
});
const albert = Albert_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  variable: "--font-albert",
  display: "swap",
});
const fsAlbert = localFont({
  src: [
    { path: "../public/fonts/fsalbert2/FSAlbertPro.woff2",    weight: "400", style: "normal" },
    { path: "../public/fonts/fsalbert2/FSAlbertPro-Italic.woff2", weight: "700", style: "bold" },
    { path: "../public/fonts/fsalbert2/FSAlbertPro-Light.woff2",  weight: "700", style: "bold" },
    { path: "../public/fonts/fsalbert2/FSAlbertPro-LightItalic.woff2",    weight: "700", style: "bold" },
    { path: "../public/fonts/fsalbert2/FSAlbertPro-Thin.woff2",    weight: "100", style: "normal" },
    { path: "../public/fonts/fsalbert2/FSAlbertPro-ThinItalic.woff2",    weight: "100", style: "normal" },
  ],
  variable: "--font-fs-albert",
  display: "swap",
});

export const metadata = {
    icons: [
    // { rel: "icon", url: "/images/logo/Logo.png", sizes: "16x16" },
    { rel: "icon", url: "/images/logo/Logo.png", sizes: "64x64" },
    
  ],
  title: "ENI Corporation",
  description: "Generated by ENI Corporation",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${fsAlbert.variable}`}>
      <head />
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${openSans.variable} ${poppins.variable} ${fsAlbert.variable} ${albert.variable} antialiased`}
      >
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}

